[package]
name = "db_access"
version = "1.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.0.0-beta.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }