name: .NET Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dotnet_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: |
        cd src
        dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json --name DSharpPlus
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore
    - name: Test
      run: |
        cd src
        dotnet test --no-build --verbosity normal
