name: .NET Build/Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dotnet_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.202
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore
    - name: Test
      run: |
        cd src
        dotnet test --no-build --verbosity normal
